config/routes.rb
Blogadding::Application.routes.draw do
  
  resources :affiliate_personals

  resources :employees

  resources :affiliates

  mount Ckeditor::Engine => '/ckeditor'
  root :to => "home#index"
  devise_for :users, :skip => [:registrations] 
  resources :users
  resources :admin, only: [:index]
  resources :blog, only: [:index, :show], as: 'blog', controller: 'blogadd'

  get "home/about", path: "about"
  get "home/affiliate", path: "affiliate"
  get "home/news", path: "news"
  get "home/links", path: "links"
  get "home/contact_us", path: "contact_us"
  get "home/news/:id/show",to: "home#show", as: "news_show"
  post "home/send_contact_message"
  get "home/search_affiliate"
  get "home/search_affiliate_professional"

  #pdfs
  get "pdfs/registration_sheet/:id", to: "pdfs#registration_sheet", as:"pdf_registration_sheet"
  get "pdfs/registration_professional/:id", to: "pdfs#registration_professional", as:"pdf_registration_professional"
  #get "pdfs/download/:document", to: "pdfs#download", as:"pdf_download"


  scope :admin do
  	resources :posts
  	resources :categories
  end

  match "/posts/add_new_comment" => "posts#add_new_comment", :as => "add_new_comment_to_posts", :via => [:post]
 
end

app/models/user.rb
class User < ActiveRecord::Base
	before_create :add_role_default

	has_many :posts, dependent: :destroy
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  def add_role_default
    if User.blank?
      self.add_role "admin"
    else 
      self.add_role "escritor"
    end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def new
    @user = User.new
  end

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'user was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation,:role_ids, :encrypted_password)
  end
end

app/views/users/_form.html.haml
= simple_form_for(@user) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name, label: false, input_html: { class: 'form-control', placeholder: "Nombre" }
    %br
    = f.input :email, label: false, input_html: { class: 'form-control', placeholder: "Email" }
    %br
    = f.input :password, label: false, input_html: { class: 'form-control', placeholder: "Contraseña" }
    %br
    = f.input :password_confirmation, label: false, input_html: { class: 'form-control', placeholder: "Confirmación de contraseña" }
    %br
  .form-actions
    = f.button :submit, "Guardar Usuario", class: "pull-right btn btn-primary"

app/views/users/_user.html.haml
.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1",:id => "role-options-#{user.id}" }
	.modal-dialog
		.modal-content
			= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
				.modal-header
					%button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
					%h1#myModalLabel.modal-title 
						%center
							Roles
				.modal-body
					= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first	
				.modal-footer
					%button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Cerrar
					= f.submit "Asignar Rol", :class => "btn btn-primary"

app/views/users/index.html.haml
= content_for(:title, "Admin - Usuarios")
%center
  %h3 Listado de usuarios
  = link_to "Nuevo Usuario", new_user_path, class: 'btn btn-success'
%table.table.datatable
  %thead
    %tr
      %th Nombre
      %th Email
      %th Role
      %th 
      %th
  %tbody
    - @users.each do |user|
      %tr
        %td= link_to user.name, user
        %td= user.email
        %td= user.roles.first.name.titleize unless user.roles.first.nil?
        %td
          %a{"data-toggle" => "modal", :href => "#role-options-#{user.id}", :type => "button"} Cambiar rol
          = render user
        %td= link_to("Eliminar usuario", user_path(user), :data => { :confirm => "Si elimina esta categoria, se eliminaran todos los posts relacionados, ¿estas seguro de querer eliminar?'" }, :method => :delete) unless user == current_user

= render "layouts/script_datatable"

app/views/users/new.html.haml
= content_for(:title, "Usuarios - Nuevo")
.container
	%center
		%h3 Agregar nuevo usuario
	= render 'form'

app/views/users/show.html.haml
= content_for(:title, "Usuario - #{@user.name}")
%h3 Usuario
%p
  Nombre: #{@user.name}
%p
  Email: #{@user.email if @user.email}