config/routes.rb
Blogadding::Application.routes.draw do
  
  resources :affiliate_personals

  resources :employees

  resources :affiliates

  mount Ckeditor::Engine => '/ckeditor'
  root :to => "home#index"
  devise_for :users, :skip => [:registrations] 
  resources :users
  resources :admin, only: [:index]
  resources :blog, only: [:index, :show], as: 'blog', controller: 'blogadd'

  get "home/about", path: "about"
  get "home/affiliate", path: "affiliate"
  get "home/news", path: "news"
  get "home/links", path: "links"
  get "home/contact_us", path: "contact_us"
  get "home/news/:id/show",to: "home#show", as: "news_show"
  post "home/send_contact_message"
  get "home/search_affiliate"
  get "home/search_affiliate_professional"

  #pdfs
  get "pdfs/registration_sheet/:id", to: "pdfs#registration_sheet", as:"pdf_registration_sheet"
  get "pdfs/registration_professional/:id", to: "pdfs#registration_professional", as:"pdf_registration_professional"
  #get "pdfs/download/:document", to: "pdfs#download", as:"pdf_download"


  scope :admin do
  	resources :posts
  	resources :categories
  end

  match "/posts/add_new_comment" => "posts#add_new_comment", :as => "add_new_comment_to_posts", :via => [:post]
 
end

app/models/affiliate_personal.rb
class AffiliatePersonal < ActiveRecord::Base

	validates_presence_of :name, :rif_personal, :profession, :ocupation, :phone, :mobile, :email, :municipality, :city, :street, :local, :sector
	validates_numericality_of :phone, :mobile, :rif_personal, :only_integer => true
	validates :email, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create, :message => "formato de email no valido" }
	validates :rif_personal, :length => { minimum: 8, maximum: 10 }, :uniqueness => true
	validates :phone, :mobile, :length => { minimum: 7, maximum: 15 }

	def self.search(search)
    where "rif_personal = '#{search}'"
  end
end

app/controllers/affiliate_personals_controller.rb
class AffiliatePersonalsController < ApplicationController
  before_action :set_affiliate_personal, only: [:show, :edit, :update, :destroy]

  # GET /affiliate_personals
  # GET /affiliate_personals.json
  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @affiliate_personals = AffiliatePersonal.all
  end

  # GET /affiliate_personals/1
  # GET /affiliate_personals/1.json
  def show
  end

  # GET /affiliate_personals/new
  def new
    @affiliate_personal = AffiliatePersonal.new
  end

  # GET /affiliate_personals/1/edit
  def edit
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
  end

  # POST /affiliate_personals
  # POST /affiliate_personals.json
  def create
    @affiliate_personal = AffiliatePersonal.new(affiliate_personal_params)

    respond_to do |format|
      if @affiliate_personal.save
        NotifyClient.notifyprofesional(@affiliate_personal).deliver
        NotifyClient.notifyparcaturprofesional(@affiliate_personal).deliver
        format.html { redirect_to @affiliate_personal, notice: 'Affiliate personal was successfully created.' }
        format.json { render action: 'show', status: :created, location: @affiliate_personal }
      else
        format.html { render action: 'new' }
        format.json { render json: @affiliate_personal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /affiliate_personals/1
  # PATCH/PUT /affiliate_personals/1.json
  def update
    respond_to do |format|
      if @affiliate_personal.update(affiliate_personal_params)
        format.html { redirect_to @affiliate_personal, notice: 'Affiliate personal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @affiliate_personal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /affiliate_personals/1
  # DELETE /affiliate_personals/1.json
  def destroy
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @affiliate_personal.destroy
    respond_to do |format|
      format.html { redirect_to affiliate_personals_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_affiliate_personal
      @affiliate_personal = AffiliatePersonal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def affiliate_personal_params
      params.require(:affiliate_personal).permit(:rif_personal, :name, :profession, :ocupation, :phone, :mobile, :email, :municipality, :city, :sector, :street, :local)
    end
end

app/helpers/affiliate_personals_helper.rb
module AffiliatePersonalsHelper
end

app/views/affiliate_personals/_form.html.haml
- unless current_user
  .col-lg-12.col-md-12.col-sm-12.col-xs-12
    .col-lg-6.col-md-6.col-sm-12.col-xs-12
      %h5{ style: "font-family: 'Raleway', sans-serif;"} Si usted ya se encuentra registrado/a por favor coloque su cédula aquí.
    = form_tag home_search_affiliate_professional_path, :method => 'get' do
      .col-lg-6.col-md-6.col-sm-12.col-xs-12{ style: "padding-left:0px;" }
        .col-lg-10.col-md-10.col-sm-10.col-xs-10{ style: "padding:0px; margin-bottom:18px;"}
          = text_field_tag :search, params[:search], class: "form-control", placeholder: "Cédula"
        .col-lg-2.col-md-2.col-sm-2.col-xs-2{ style: "padding-left:2px;" }
          = submit_tag "Buscar", :name => nil, class: "btn btn-success"
= simple_form_for(@affiliate_personal) do |f|
  = f.error_notification
  .col-lg-12.col-md-12.col-sm-12.col-xs-12
    .widget
      .widget-header{ style: 'background-color: #26bf28;'}
        %h4 Datos del Profesional
      .widget-content.row{ style: 'padding:10px; padding-top:20px;'} 
        .col-lg-6.col-md-6.col-sm-12.col-xs-12
          = f.input :rif_personal, label:false, input_html: { class: 'form-control', placeholder: "Cédula" }
          %br/
          = f.input :name, label:false, input_html: { class: 'form-control', placeholder: "Nombres y apellidos" }
          %br/
          = f.input :profession, label:false, input_html: { class: 'form-control', placeholder: "Profesión" }
          %br/
          = f.input :ocupation, label:false, input_html: { class: 'form-control', placeholder: "Ocupación" }
          %br/
          = f.input :phone, label:false, input_html: { class: 'form-control', placeholder: "Teléfono de habitación" }
          %br/
          = f.input :mobile, label:false, input_html: { class: 'form-control', placeholder: "Teléfono celular" }
          %br/
          = f.input :email, label:false, input_html: { class: 'form-control', placeholder: "Email" }
        .col-lg-6.col-md-6.col-sm-12.col-xs-12
          = f.input :municipality, label: false, collection: ["Carirubana", "Falcón", "Los Taques"], include_blank: "- Municipio -" , input_html: { class: "form-control" }
          %br/
          = f.input :city, label:false, input_html: { class: 'form-control', placeholder: "Ciudad" }
          %br/
          = f.input :sector, label:false, input_html: { class: 'form-control', placeholder: "Sector" }
          %br/
          = f.input :street, label:false, input_html: { class: 'form-control', placeholder: "Calle/Avenida" }
          %br/
          = f.input :local, label:false, input_html: { class: 'form-control', placeholder: "Casa/Apto/Edif" }

  .col-lg-12.col-md-12.col-sm-12.col-xs-12{ style: "margin-bottom:15px;"}
    .form-actions
      = f.button :submit, "Guardar Afiliación", class: 'btn btn-primary pull-right'

app/views/affiliate_personals/edit.html.haml
= content_for(:title, "Afiliaciones - Editar")
%h1 Editar Afiliación

= render 'form'

app/views/affiliate_personals/index.html.haml
= content_for(:title, "Admin - Afiliaciones de profesionales")
%center
  %h1 Listado de Afiliaciones

%table.table.datatable
  %thead
    %tr
      %th Cédula
      %th Nombre
      %th Profesión
      %th Teléfono 
      %th Email
      %th
      %th
      %th

  - @affiliate_personals.each do |affiliate|
    %tr
      %td= affiliate.rif_personal
      %td= affiliate.name
      %td= affiliate.profession
      %td= affiliate.phone
      %td= affiliate.email
      %td= link_to 'Vista previa', affiliate
      %td= link_to 'Editar', edit_affiliate_personal_path(affiliate)
      %td= link_to 'Eliminar', affiliate, :method => :delete, :data => { :confirm => '¿Estas seguro de querer eliminar esta afiliación?' }

%br

= render "layouts/script_datatable"

app/views/affiliate_personals/new.html.haml
= content_for(:title, "Parcatur - Nueva afiliación")
%section.affiliate
	= render 'layouts/messages'
	.container
		.title
			%h1 Formulario de afilación
			%hr
		= render 'form'
	= render "layouts/footertwo"

app/views/affiliate_personals/show.html.haml
= content_for(:title, "#{@affiliate_personal.name}")
%section.affiliate
  .container
    .title
      %h1 
        = "Datos de "+@affiliate_personal.name
      %hr
    %p#notice= notice

    .col-lg-12.col-md-12.col-sm-12.col-xs-12
      .show-body{ style: "padding: 10px;"}
        %p
          %b Cédula:
          = @affiliate_personal.rif_personal
        %p
          %b Nombre:
          = @affiliate_personal.name
        %p
          %b Profesión:
          = @affiliate_personal.profession
        %p
          %b Ocupación:
          = @affiliate_personal.ocupation
        %p
          %b Télefono de habitación:
          = @affiliate_personal.phone
        %p
          %b Télefono de celular:
          = @affiliate_personal.mobile
        %p
          %b Email:
          = @affiliate_personal.email
        %p
          %b Direción:
          = "#{@affiliate_personal.city}, #{@affiliate_personal.municipality}, #{@affiliate_personal.sector}, #{@affiliate_personal.street}, #{@affiliate_personal.local}"
    .col-lg-12.col-md-12.col-sm-12.col-xs-12{ style:"margin-top:40px; margin-bottom: 60px; width:100%" }
      = link_to "Descargar planilla", pdf_registration_professional_path(@affiliate_personal.id, format: :pdf), class: 'btn btn-primary'


= render "layouts/footertwo"
    