config/routes.rb
Blogadding::Application.routes.draw do
  
  resources :affiliate_personals

  resources :employees

  resources :affiliates

  mount Ckeditor::Engine => '/ckeditor'
  root :to => "home#index"
  devise_for :users, :skip => [:registrations] 
  resources :users
  resources :admin, only: [:index]
  resources :blog, only: [:index, :show], as: 'blog', controller: 'blogadd'

  get "home/about", path: "about"
  get "home/affiliate", path: "affiliate"
  get "home/news", path: "news"
  get "home/links", path: "links"
  get "home/contact_us", path: "contact_us"
  get "home/news/:id/show",to: "home#show", as: "news_show"
  post "home/send_contact_message"
  get "home/search_affiliate"
  get "home/search_affiliate_professional"

  #pdfs
  get "pdfs/registration_sheet/:id", to: "pdfs#registration_sheet", as:"pdf_registration_sheet"
  get "pdfs/registration_professional/:id", to: "pdfs#registration_professional", as:"pdf_registration_professional"
  #get "pdfs/download/:document", to: "pdfs#download", as:"pdf_download"


  scope :admin do
  	resources :posts
  	resources :categories
  end

  match "/posts/add_new_comment" => "posts#add_new_comment", :as => "add_new_comment_to_posts", :via => [:post]
 
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_commentable
	belongs_to :user
  belongs_to :category
  mount_uploader :image, ImageUploader

  validates_presence_of :title, :content, :user_id, :category_id, :image
  validate :picture_size_validation, :if => "image?"  
	#search
  def self.search(search)
    if search
      @post = find(:all, :conditions => ['public = ? AND title iLIKE ? OR content iLIKE ?', true, ["%#{search}%"]*2].flatten)
    else
      @post = where('public = true').order('id DESC')
    end
  end

  def picture_size_validation
    errors[:image] << "Imagén no puede pesar más de 1 MB" if self.image.size > 1.megabytes
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /posts
  # GET /posts.json
  def index
    if current_user.has_role? :admin 
      @posts = Post.all

    else
      @posts = Post.where(user_id: current_user.id)
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    if @post.user_id != current_user.id and current_user.roles.first != "admin" 
      authorize! :index, @user, :message => 'Necesita autorización de administrador para poder ver este post.'
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    if current_user.roles.first.name != "admin"
      if Post.find(params[:id]).user_id != current_user.id #evitar que un usuario no admin pueda evitar otro post que no sea de su propiedad
        raise CanCan::AccessDenied.new("No esta autorizado para editar este post.", :edit, Post)
      end
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  #añadir comentario al post
  def add_new_comment
    post = Post.find(params[:id])
    post.comments << Comment.new(comment: params[:comment], user_id: params[:user_id], name: params[:name])
    redirect_to blog_path(post.id, anchor: 'comment-area')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :public, :category_id, :user_id, :image)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
= simple_form_for(@post) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title, label: false, input_html: { class: 'form-control', placeholder: "Título" }
    %br
    = f.input :category_id, collection: Category.all(order: 'name'), prompt: "Seleccionar categoría", label: false, input_html: { class: 'form-control' }
    %br
    = f.cktext_area :content, :placeholder => 'Escribir un artírculo'
    %br
    .col.md-12
      .col-lg-6.col-md-6
        - unless @post.image.blank?
          = image_tag f.object.image_url, width: "130px", style: "margin-left: 0px;"
        %br
        = f.input :image, label: false, input_html: { id: 'file-upload' }, as: :file
      .col-lg-6.col-md-6
        = f.input :public, :as => :boolean, label: "¿Publicar?", :input_html => { style: 'margin: 0px;'}
        = f.input :user_id, label: false, input_html: { class: 'form-control', value: "#{current_user.id}"}, as: :hidden
  .form-actions.col-lg-12.col-md-12
    = f.button :submit, "Guardar Post", class: "pull-right btn btn-primary"

app/views/posts/edit.html.haml
= content_for(:title, "Posts - Editar")
.container.forms
	%center
		%h3 Editar Post
	= render 'form'

app/views/posts/index.html.haml
= content_for(:title, "Admin - Posts")
%center
	%h3 Listado de posts
	= link_to "Nuevo Post", new_post_path, class: 'btn btn-success'

%table.table.datatable
	%thead
		%tr
			%th Título
			%th ¿Publicado?
			%th Categoría
			%th Autor
			%th 
			%th 
			%th 

	- @posts.each do |post|
		%tr
			%td= post.title
			%td= post.public ? "Si" : "No"
			%td= post.category.name
			%td= post.user.name
			%td= link_to 'Vista previa', post
			%td= link_to 'Editar', edit_post_path(post)
			%td= link_to 'Eliminar', post, :method => :delete, :data => { :confirm => '¿Estas seguro de querer eliminar?' }



= render "layouts/script_datatable"

app/views/posts/new.html.haml
= content_for(:title, "Posts - Nuevo")
.container.forms
	%center
		%h3 Nuevo Post
	= render 'form'

app/views/posts/show.html.haml
= content_for(:title, "Posts - #{@post.title}")
%p
  %b Imagen principal:
  = image_tag @post.image, width: "300px"
%p
  %b Título:
  = @post.title
%p
  %b Contenido:
  = @post.content.html_safe
%p
  %b ¿Artículo publicado?
  = @post.public ? "Si" : "No"
%p
  %b Categoría:
  = @post.category.name
%p
  %b Autor:
  = @post.user.name