config/routes.rb
Blogadding::Application.routes.draw do
  
  resources :affiliate_personals

  resources :employees

  resources :affiliates

  mount Ckeditor::Engine => '/ckeditor'
  root :to => "home#index"
  devise_for :users, :skip => [:registrations] 
  resources :users
  resources :admin, only: [:index]
  resources :blog, only: [:index, :show], as: 'blog', controller: 'blogadd'

  get "home/about", path: "about"
  get "home/affiliate", path: "affiliate"
  get "home/news", path: "news"
  get "home/links", path: "links"
  get "home/contact_us", path: "contact_us"
  get "home/news/:id/show",to: "home#show", as: "news_show"
  post "home/send_contact_message"
  get "home/search_affiliate"
  get "home/search_affiliate_professional"

  #pdfs
  get "pdfs/registration_sheet/:id", to: "pdfs#registration_sheet", as:"pdf_registration_sheet"
  get "pdfs/registration_professional/:id", to: "pdfs#registration_professional", as:"pdf_registration_professional"
  #get "pdfs/download/:document", to: "pdfs#download", as:"pdf_download"


  scope :admin do
  	resources :posts
  	resources :categories
  end

  match "/posts/add_new_comment" => "posts#add_new_comment", :as => "add_new_comment_to_posts", :via => [:post]
 
end

app/models/category.rb
class Category < ActiveRecord::Base
	validates_presence_of :name
	has_many :posts, dependent: :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
  end

  # GET /categories/new
  def new
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
= simple_form_for(@category) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name, label: false,input_html: { class: 'form-control', placeholder: "Nombre" }
  %br
  .form-actions
    = f.button :submit, "Guardar Categoría", class: "pull-right btn btn-primary"

app/views/categories/edit.html.haml
= content_for(:title, "Categorías - Editar")
.container.forms
	%center
		%h3 Editar Categoría

= render 'form'

app/views/categories/index.html.haml
= content_for(:title, "Admin - Categorías")
%center
  %h1 Listado de categorías
  = link_to "Nueva Categoría", new_category_path, class: 'btn btn-success'

%table.table.datatable
  %thead
    %tr
      %th Nombre
      %th 
      %th 
      %th 

  - @categories.each do |category|
    %tr
      %td= category.name
      %td= link_to 'Vista previa', category
      %td= link_to 'Editar', edit_category_path(category)
      %td= link_to 'Eliminar', category, :method => :delete, :data => { :confirm => 'Si elimina esta categoria, se eliminaran todos los posts relacionados, ¿estas seguro de querer eliminar?' }

%br

= render "layouts/script_datatable"

app/views/categories/new.html.haml
= content_for(:title, "Categorías - Nueva")
%h1 Nueva Categoría

= render 'form'

app/views/categories/show.html.haml
= content_for(:title, "Categoriás - #{@category.name}")
%p
  %b Nombre:
  = @category.name